/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

use std::any::TypeId;
use std::cell::UnsafeCell;
use std::marker::PhantomData;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::OnceLock;

use tvm_ffi_sys::TVMFFITypeIndex as TypeIndex;

use crate::{AnyCompatible, AnyView};

/// A call-site-local arm number generated by `match_any!`.
#[doc(hidden)]
pub type ArmId = u32;

/// Internal map from runtime object type indices to call-site-local arm numbers.
///
/// The table stores only [`ArmId`] values. Arm bodies remain native branches in
/// the macro expansion and are never stored as functions or closures.
#[doc(hidden)]
#[repr(C)]
pub struct LeafLookupTable<const CAPACITY: usize> {
    seen_once: AtomicBool,
    pattern_list_id: OnceLock<TypeId>,
    dense_base_type_index: UnsafeCell<i32>,
    arm_by_type_index: UnsafeCell<[(i32, ArmId); CAPACITY]>,
}

// `pattern_list_id` publishes completion with release/acquire synchronization.
// The slots are written only by its initializer and are immutable afterwards.
unsafe impl<const CAPACITY: usize> Sync for LeafLookupTable<CAPACITY> {}

impl<const CAPACITY: usize> LeafLookupTable<CAPACITY> {
    const EMPTY_TYPE_INDEX: i32 = 0;

    #[doc(hidden)]
    pub const fn new() -> Self {
        assert!(
            CAPACITY.is_power_of_two(),
            "match_any! leaf lookup capacity must be a power of two"
        );
        Self {
            seen_once: AtomicBool::new(false),
            pattern_list_id: OnceLock::new(),
            dense_base_type_index: UnsafeCell::new(Self::EMPTY_TYPE_INDEX),
            arm_by_type_index: UnsafeCell::new([(Self::EMPTY_TYPE_INDEX, 0); CAPACITY]),
        }
    }

    #[doc(hidden)]
    #[inline(always)]
    pub fn pattern_list_id(&self) -> Option<TypeId> {
        self.pattern_list_id.get().copied()
    }

    /// Returns `true` after the call site has already used the ordered path once.
    #[doc(hidden)]
    #[inline(always)]
    pub fn should_initialize(&self) -> bool {
        if self.seen_once.load(Ordering::Relaxed) {
            true
        } else {
            // This is only a one-shot-cost heuristic. Concurrent callers may
            // both use the ordered path; a later call will still initialize.
            self.seen_once.store(true, Ordering::Relaxed);
            false
        }
    }

    #[doc(hidden)]
    #[cold]
    #[inline(never)]
    pub fn initialize<const N: usize>(
        &self,
        pattern_list_id: TypeId,
        type_indices: [i32; N],
    ) -> Result<(), ()> {
        let initialized_pattern_list_id = self.pattern_list_id.get_or_init(|| {
            let (min_type_index, max_type_index) =
                Self::validate_and_find_range::<N>(&type_indices);

            // SAFETY: OnceLock runs this closure at most once. Validation cannot
            // panic after this point, and OnceLock publishes every slot write
            // before another thread can observe the initialized pattern ID.
            let entries = unsafe { &mut *self.arm_by_type_index.get() };
            let dense_span = max_type_index
                .checked_sub(min_type_index)
                .and_then(|span| span.checked_add(1))
                .map(|span| span as usize);
            let dense_capacity = std::mem::size_of_val(entries);
            if N < u8::MAX as usize && dense_span.is_some_and(|span| span <= dense_capacity) {
                let dense_entries = unsafe {
                    std::slice::from_raw_parts_mut(
                        entries.as_mut_ptr().cast::<u8>(),
                        dense_capacity,
                    )
                };
                for (arm_id, type_index) in type_indices.into_iter().enumerate() {
                    let slot = &mut dense_entries[(type_index - min_type_index) as usize];
                    if *slot == 0 {
                        *slot = arm_id as u8 + 1;
                    }
                }
                unsafe {
                    *self.dense_base_type_index.get() = min_type_index;
                }
            } else {
                for (arm_id, type_index) in type_indices.into_iter().enumerate() {
                    Self::insert(entries, type_index, arm_id as ArmId);
                }
            }
            pattern_list_id
        });

        if initialized_pattern_list_id != &pattern_list_id {
            return Err(());
        }
        Ok(())
    }

    #[inline(always)]
    fn validate_and_find_range<const N: usize>(type_indices: &[i32; N]) -> (i32, i32) {
        assert!(N != 0, "match_any! leaf lookup requires at least one arm");
        assert!(
            CAPACITY.is_power_of_two() && CAPACITY > N,
            "match_any! leaf lookup capacity must be a power of two above the arm count"
        );
        let mut min_type_index = i32::MAX;
        let mut max_type_index = i32::MIN;
        for &type_index in type_indices {
            assert!(
                type_index >= TypeIndex::kTVMFFIStaticObjectBegin as i32,
                "match_any! leaf pattern returned a non-object type index"
            );
            min_type_index = min_type_index.min(type_index);
            max_type_index = max_type_index.max(type_index);
        }
        (min_type_index, max_type_index)
    }

    #[inline(always)]
    fn insert(arm_by_type_index: &mut [(i32, ArmId); CAPACITY], type_index: i32, arm_id: ArmId) {
        let mut offset = Self::hash(type_index);
        loop {
            let slot = &mut arm_by_type_index[offset];
            if slot.0 == Self::EMPTY_TYPE_INDEX {
                *slot = (type_index, arm_id);
                return;
            }
            // The first source arm for a duplicate type wins.
            if slot.0 == type_index {
                return;
            }
            offset = (offset + 1) & (CAPACITY - 1);
        }
    }

    /// Looks up a type after initialization.
    ///
    /// # Safety
    ///
    /// The caller must first observe a matching ID from [`Self::pattern_list_id`]
    /// or successfully call [`Self::initialize`].
    #[doc(hidden)]
    #[inline(always)]
    pub unsafe fn lookup_after_init(&self, type_index: i32) -> Option<ArmId> {
        // SAFETY: callers reach this method only after acquiring the initialized
        // pattern ID from OnceLock. The initializer never mutates slots again.
        let arm_by_type_index = unsafe { &*self.arm_by_type_index.get() };
        let dense_base_type_index = unsafe { *self.dense_base_type_index.get() };
        if dense_base_type_index != Self::EMPTY_TYPE_INDEX {
            let offset = type_index.wrapping_sub(dense_base_type_index) as usize;
            let dense_entries = unsafe {
                std::slice::from_raw_parts(
                    arm_by_type_index.as_ptr().cast::<u8>(),
                    std::mem::size_of_val(arm_by_type_index),
                )
            };
            let encoded_arm_id = dense_entries.get(offset).copied().unwrap_or(0);
            return encoded_arm_id.checked_sub(1).map(ArmId::from);
        }
        let mut offset = Self::hash(type_index);
        loop {
            let (entry_type_index, arm_id) = arm_by_type_index[offset];
            if entry_type_index == Self::EMPTY_TYPE_INDEX {
                return None;
            }
            if entry_type_index == type_index {
                return Some(arm_id);
            }
            offset = (offset + 1) & (CAPACITY - 1);
        }
    }

    #[inline(always)]
    fn hash(type_index: i32) -> usize {
        let type_index = type_index as u32;
        (type_index ^ (type_index >> 1)) as usize & (CAPACITY - 1)
    }
}

/// Type-level list used to collect leaf object-pattern metadata.
#[doc(hidden)]
pub trait LeafPatternList: 'static {
    #[doc(hidden)]
    const ALL_EXACT_LEAF: bool;

    #[doc(hidden)]
    fn fill_leaf_type_indices(out: &mut [i32]);
}

impl LeafPatternList for () {
    const ALL_EXACT_LEAF: bool = true;

    fn fill_leaf_type_indices(out: &mut [i32]) {
        debug_assert!(out.is_empty());
    }
}

impl<Head, Tail> LeafPatternList for (Head, Tail)
where
    Head: AnyCompatible + 'static,
    Tail: LeafPatternList,
{
    const ALL_EXACT_LEAF: bool = Head::MATCH_ANY_EXACT && Tail::ALL_EXACT_LEAF;

    fn fill_leaf_type_indices(out: &mut [i32]) {
        let (head, tail) = out
            .split_first_mut()
            .expect("match_any! pattern metadata length mismatch");
        *head = Head::match_any_exact_type_index();
        Tail::fill_leaf_type_indices(tail);
    }
}

/// Probe used by the macro to retain ordered matching for non-leaf patterns.
#[doc(hidden)]
pub struct LeafPatternProbe<T>(PhantomData<fn() -> T>);

impl<T> LeafPatternProbe<T> {
    #[doc(hidden)]
    pub const fn new() -> Self {
        Self(PhantomData)
    }
}

/// Leaf metadata with an autoref fallback for non-`AnyCompatible` patterns.
#[doc(hidden)]
pub trait LeafPatternMetadata {
    #[doc(hidden)]
    fn leaf_pattern_list_id(&self) -> Option<TypeId> {
        None
    }

    #[doc(hidden)]
    fn fill_leaf_type_indices(&self, _out: &mut [i32]) {}
}

impl<T> LeafPatternMetadata for &LeafPatternProbe<T> {}

impl<T: LeafPatternList> LeafPatternMetadata for LeafPatternProbe<T> {
    fn leaf_pattern_list_id(&self) -> Option<TypeId> {
        T::ALL_EXACT_LEAF.then(TypeId::of::<T>)
    }

    fn fill_leaf_type_indices(&self, out: &mut [i32]) {
        T::fill_leaf_type_indices(out);
    }
}

/// Compile-time probe for a conversion whose exact type was already selected.
#[doc(hidden)]
pub trait LeafPatternValue<T> {
    #[doc(hidden)]
    unsafe fn copy_after_leaf_match(&self, _view: AnyView<'_>) -> Option<T> {
        None
    }
}

impl<T> LeafPatternValue<T> for &LeafPatternProbe<T> {}

impl<T: AnyCompatible> LeafPatternValue<T> for LeafPatternProbe<T> {
    #[inline(always)]
    unsafe fn copy_after_leaf_match(&self, view: AnyView<'_>) -> Option<T> {
        Some(unsafe { view.copy_after_check::<T>() })
    }
}

/// Compile-time probe for a wildcard pattern that needs no converted value.
#[doc(hidden)]
pub trait PatternMatchWithoutCopy<T> {
    #[doc(hidden)]
    fn matches_without_copy(&self, _view: AnyView<'_>) -> Option<bool> {
        None
    }
}

impl<T> PatternMatchWithoutCopy<T> for &LeafPatternProbe<T> {}

impl<T: AnyCompatible> PatternMatchWithoutCopy<T> for LeafPatternProbe<T> {
    #[inline(always)]
    fn matches_without_copy(&self, view: AnyView<'_>) -> Option<bool> {
        T::MATCH_ANY_EXACT.then(|| view.type_index() == T::match_any_exact_type_index())
    }
}
